[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.20"
optimizer = true
optimizer_runs = 20_000
remappings = [
  "erc721a/=lib/ERC721A/contracts/",
  "solady/=lib/solady/src/",
  "closedsea/=lib/closedsea/src/"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config